CREATE TABLE users (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
registration_date DATE NOT NULL,
tel VARCHAR(50) NOT NULL
);

CREATE TABLE authors (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
lastName VARCHAR(255) NOT NULL UNIQUE,
);

CREATE TABLE genre (
    id BIGSERIAL PRIMARY KEY,
    genre VARCHAR(255) NOT NULL
);



CREATE TABLE books (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(50) NOT NULL,
    publication_date DATE NOT NULL,
    category_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES genre(id)
);


CREATE TABLE loans (
id BIGSERIAL PRIMARY KEY,
user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
loan_date DATE NOT NULL,
loan_return DATE,
status VARCHAR(50) NOT NULL
);